spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-expiration-ms: 900000 # 15 minutes
  refresh-expiration-ms: 2592000000 # 30 days

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
