services:
  postgres:
    image: postgres:17.4-alpine
    container_name: auth-service-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER:-auth_service_root}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD:-auth_service_password}
      POSTGRES_DB: ${AUTH_POSTGRES_DB:-auth_service_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: