services:
  postgres:
    image: postgres:17.4-alpine
    container_name: auth-service-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: