services:
  mongo:
    image: mongo:8.0.9
    container_name: payment-service-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-payment_service_root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-payment_service_root_password}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8.0.0-alpine
    container_name: payment-service-redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-payment_service_redis_password}
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: