services:
  postgres:
    image: postgres:17.4-alpine
    container_name: account-service-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.0-alpine
    container_name: account-service-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redispassword
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: